os: linux
language: python
python:
  - 3.9

env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - export IMAGE_VERSION=${TRAVIS_BRANCH//\//\_}
  - export IMAGE_VERSION=${IMAGE_VERSION//\#/\_}

  # Install docker with buildx
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - lsb_release -cs
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
  - cat /proc/sys/fs/binfmt_misc/qemu-aarch64

install:
  # Install dependencies
  - (cd app && pip install -r requirements.txt)

  # Install dev dependencies
  - (cd app && pip install -r requirements.dev.txt)

  # Code static analysis
  - (cd app && autopep8 --in-place --aggressive --aggressive *.py)

  # Run UT (todo)

script:
  # Build docker image
  - docker build -t tydom2mqtt .

after_success:
  # Override image version with latest if master branch
  - if [ "$TRAVIS_BRANCH" == "master" ] ; then export IMAGE_VERSION=latest; fi

  # Override image version with tag name if any
  - if [ ! -z "$TRAVIS_TAG" ] ; then export IMAGE_VERSION=$TRAVIS_TAG; fi

  # Build & push image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make prepare
  - make build IMAGE_NAME=tydom2mqtt IMAGE_VERSION=$IMAGE_VERSION PLATFORMS=linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64 DOCKER_USERNAME=$DOCKER_USERNAME
